// This file represents ONE student's Present/Absent mark inside a session

// An "enum" is just a fixed list of allowed values.
// Instead of typing "Present" or "present" or "PRESENT" (typos!), we use this instead.
enum AttendanceStatus { present, absent }

// This is a small helper that converts our enum to/from the text SQLite stores
extension AttendanceStatusX on AttendanceStatus {
  // Converts enum -> text before saving to SQLite
  String get dbValue {
    if (this == AttendanceStatus.present) return 'Present';
    return 'Absent';
  }

  // Converts text -> enum after reading from SQLite
  static AttendanceStatus fromDbValue(String value) {
    if (value == 'Present') return AttendanceStatus.present;
    if (value == 'Absent') return AttendanceStatus.absent;
    throw ArgumentError('Unknown attendance status: $value');
  }
}

class AttendanceRecord {
  final int? recordId; // Auto-generated by SQLite
  final int sessionId; // Which session this record belongs to
  final int studentId; // Which student this record is about
  final AttendanceStatus status; // Present or Absent

  const AttendanceRecord({
    this.recordId,
    required this.sessionId,
    required this.studentId,
    required this.status,
  });

  Map<String, dynamic> toMap() {
    return {
      'record_id': recordId,
      'session_id': sessionId,
      'student_id': studentId,
      'status': status.dbValue, // enum converted to text here
    };
  }

  factory AttendanceRecord.fromMap(Map<String, dynamic> map) {
    return AttendanceRecord(
      recordId: map['record_id'] as int?,
      sessionId: map['session_id'] as int,
      studentId: map['student_id'] as int,
      status: AttendanceStatusX.fromDbValue(map['status'] as String),
    );
  }

  @override
  String toString() =>
      'AttendanceRecord(session: $sessionId, student: $studentId, status: ${status.dbValue})';
}
