// This file represents ONE Attendance Session
// Example: "Teacher Rahul took Maths attendance on 2026-07-04 at 10:00 AM"

class AttendanceSession {
  final int? sessionId; // Auto-generated by SQLite
  final int teacherId; // Which teacher took this session
  final int subjectId; // Which subject (saved again here for history safety)
  final String sessionDate; // Format: "2026-07-04"
  final String sessionTime; // Format: "10:00:00"
  final String createdAt;

  const AttendanceSession({
    this.sessionId,
    required this.teacherId,
    required this.subjectId,
    required this.sessionDate,
    required this.sessionTime,
    required this.createdAt,
  });

  Map<String, dynamic> toMap() {
    return {
      'session_id': sessionId,
      'teacher_id': teacherId,
      'subject_id': subjectId,
      'session_date': sessionDate,
      'session_time': sessionTime,
      'created_at': createdAt,
    };
  }

  factory AttendanceSession.fromMap(Map<String, dynamic> map) {
    return AttendanceSession(
      sessionId: map['session_id'] as int?,
      teacherId: map['teacher_id'] as int,
      subjectId: map['subject_id'] as int,
      sessionDate: map['session_date'] as String,
      sessionTime: map['session_time'] as String,
      createdAt: map['created_at'] as String,
    );
  }

  @override
  String toString() =>
      'AttendanceSession(id: $sessionId, date: $sessionDate, time: $sessionTime)';
}
