// This file represents ONE Student

class Student {
  final int? studentId; // Auto-generated by SQLite
  final String name; // Student's name
  final String rollNumber; // Unique roll number (e.g. "21CE045")
  final bool isActive; // true = active student, false = "deleted" (soft delete)
  final String createdAt; // When this student was added

  const Student({
    this.studentId,
    required this.name,
    required this.rollNumber,
    this.isActive = true, // Default: every new student is active
    required this.createdAt,
  });

  // Convert to Map for SQLite
  // Note: SQLite has no "true/false" type, so we store 1 for true, 0 for false
  Map<String, dynamic> toMap() {
    return {
      'student_id': studentId,
      'name': name,
      'roll_number': rollNumber,
      'is_active': isActive ? 1 : 0,
      'created_at': createdAt,
    };
  }

  // Convert from Map back into a Student object
  factory Student.fromMap(Map<String, dynamic> map) {
    return Student(
      studentId: map['student_id'] as int?,
      name: map['name'] as String,
      rollNumber: map['roll_number'] as String,
      isActive:
          (map['is_active'] as int) == 1, // 1 becomes true, 0 becomes false
      createdAt: map['created_at'] as String,
    );
  }

  @override
  String toString() =>
      'Student(id: $studentId, name: $name, roll: $rollNumber)';
}
