// This file represents ONE Teacher

class Teacher {
  final int? teacherId; // Auto-generated by SQLite, null when creating new
  final String teacherCode; // The ID teacher types to log in (e.g. "T101")
  final String name; // Teacher's full name
  final String
  passwordHash; // We NEVER store plain passwords - always a hashed version
  final int
  subjectId; // Which subject this teacher teaches (links to Subject table)
  final String createdAt; // When this teacher was added (timestamp)

  const Teacher({
    this.teacherId,
    required this.teacherCode,
    required this.name,
    required this.passwordHash,
    required this.subjectId,
    required this.createdAt,
  });

  // Convert to Map (for saving into SQLite)
  Map<String, dynamic> toMap() {
    return {
      'teacher_id': teacherId,
      'teacher_code': teacherCode,
      'name': name,
      'password_hash': passwordHash,
      'subject_id': subjectId,
      'created_at': createdAt,
    };
  }

  // Convert from Map (reading from SQLite)
  factory Teacher.fromMap(Map<String, dynamic> map) {
    return Teacher(
      teacherId: map['teacher_id'] as int?,
      teacherCode: map['teacher_code'] as String,
      name: map['name'] as String,
      passwordHash: map['password_hash'] as String,
      subjectId: map['subject_id'] as int,
      createdAt: map['created_at'] as String,
    );
  }

  @override
  String toString() =>
      'Teacher(id: $teacherId, name: $name, code: $teacherCode)';
}
